pipeline {
    agent any

    stages {

        stage('Deploy') {
            steps {
                script {
                    bat 'xcopy /E /I * "C:\\Users\\p\\Downloads\\apache-tomcat-8.0.1-windows-i64\\apache-tomcat-8.0.1\\webapps\\MyJSP"'
                }
            }
        }

        stage('Test') {
            steps {
                echo "JSP files deployed successfully"
            }
        }

        stage('Restart Server') {
            steps {
                script {
                    bat 'C:\\Users\\p\\Downloads\\apache-tomcat-8.0.1-windows-i64\\apache-tomcat-8.0.1\\bin\\shutdown.bat'
                    bat 'C:\\Users\\p\\Downloads\\apache-tomcat-8.0.1-windows-i64\\apache-tomcat-8.0.1\\bin\\startup.bat'
                }
            }
        }
    }
}